"""Add Telnyx support to assistants

Revision ID: 05e7989a91e8
Revises: 78b353b3c139
Create Date: 2025-08-11 20:53:01.336749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05e7989a91e8'
down_revision: Union[str, None] = '78b353b3c139'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assistants', sa.Column('telnyx_api_key', sa.String(length=255), nullable=True))
    op.add_column('assistants', sa.Column('telnyx_connection_id', sa.String(length=255), nullable=True))
    # op.alter_column('assistants', 'phone_number',
    #            existing_type=sa.VARCHAR(length=20),
    #            nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assistants', 'phone_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.drop_column('assistants', 'telnyx_connection_id')
    op.drop_column('assistants', 'telnyx_api_key')
    # ### end Alembic commands ###
