"""storing chat in database now.

Revision ID: 2bd220ec6136
Revises: 40d7451dbc37
Create Date: 2025-06-01 01:06:31.534026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bd220ec6136'
down_revision: Union[str, None] = '40d7451dbc37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('call_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('message_index', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('llm_provider', sa.String(length=50), nullable=True),
    sa.Column('llm_model', sa.String(length=100), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('message_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_call_message_index', 'chat_messages', ['call_id', 'message_index'], unique=True)
    op.create_index(op.f('ix_chat_messages_call_id'), 'chat_messages', ['call_id'], unique=False)
    op.create_index(op.f('ix_chat_messages_role'), 'chat_messages', ['role'], unique=False)
    op.create_table('webhook_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('call_id', sa.Integer(), nullable=False),
    sa.Column('assistant_id', sa.Integer(), nullable=False),
    sa.Column('webhook_url', sa.String(length=1000), nullable=False),
    sa.Column('webhook_type', sa.String(length=50), nullable=False),
    sa.Column('request_payload', sa.JSON(), nullable=False),
    sa.Column('request_headers', sa.JSON(), nullable=True),
    sa.Column('response_status_code', sa.Integer(), nullable=True),
    sa.Column('response_body', sa.Text(), nullable=True),
    sa.Column('response_headers', sa.JSON(), nullable=True),
    sa.Column('attempted_at', sa.DateTime(), nullable=False),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('webhook_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['assistant_id'], ['assistants.id'], ),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_logs_assistant_id'), 'webhook_logs', ['assistant_id'], unique=False)
    op.create_index(op.f('ix_webhook_logs_call_id'), 'webhook_logs', ['call_id'], unique=False)
    op.create_index(op.f('ix_webhook_logs_webhook_type'), 'webhook_logs', ['webhook_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_webhook_logs_webhook_type'), table_name='webhook_logs')
    op.drop_index(op.f('ix_webhook_logs_call_id'), table_name='webhook_logs')
    op.drop_index(op.f('ix_webhook_logs_assistant_id'), table_name='webhook_logs')
    op.drop_table('webhook_logs')
    op.drop_index(op.f('ix_chat_messages_role'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_call_id'), table_name='chat_messages')
    op.drop_index('idx_call_message_index', table_name='chat_messages')
    op.drop_table('chat_messages')
    # ### end Alembic commands ###
