"""add_transfer_call_message_field

Revision ID: 36ff47847970
Revises: b51d20b49e89
Create Date: 2025-05-22 19:37:58.657353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36ff47847970'
down_revision: Union[str, None] = 'b51d20b49e89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assistants', sa.Column('transfer_call_message', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assistants', 'transfer_call_message')
    # ### end Alembic commands ###
