"""Add messaging_service_sid to Assistant model

Revision ID: 37832f2fb727
Revises: f7c7060547e6
Create Date: 2025-08-20 03:53:42.170852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37832f2fb727'
down_revision: Union[str, None] = 'f7c7060547e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assistants', sa.Column('messaging_service_sid', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assistants', 'messaging_service_sid')
    # ### end Alembic commands ###
