"""added inworld support

Revision ID: 388bbca882dc
Revises: e8640877db1f
Create Date: 2025-06-29 20:34:44.342943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '388bbca882dc'
down_revision: Union[str, None] = 'e8640877db1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assistants', sa.Column('inworld_bearer_token', sa.String(length=255), nullable=True))
    op.add_column('assistants', sa.Column('inworld_workspace_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assistants', 'inworld_workspace_id')
    op.drop_column('assistants', 'inworld_bearer_token')
    # ### end Alembic commands ###
