"""added fallback support

Revision ID: 40d7451dbc37
Revises: 45d759ed5c5b
Create Date: 2025-05-31 12:27:44.002650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40d7451dbc37'
down_revision: Union[str, None] = '45d759ed5c5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assistants', sa.Column('llm_fallback_providers', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assistants', 'llm_fallback_providers')
    # ### end Alembic commands ###
