"""Add provider support to phone_numbers table

Revision ID: 499e40be4242
Revises: 05e7989a91e8
Create Date: 2025-08-13 20:13:10.148479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '499e40be4242'
down_revision: Union[str, None] = '05e7989a91e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('assistants_phone_number_key', 'assistants', type_='unique')
    op.drop_column('assistants', 'phone_number')
    op.add_column('organizations', sa.Column('telnyx_api_key', sa.String(length=255), nullable=True))
    op.add_column('organizations', sa.Column('telnyx_connection_id', sa.String(length=255), nullable=True))
    
    # Add provider column as nullable first
    op.add_column('phone_numbers', sa.Column('provider', sa.String(length=20), nullable=True))
    op.add_column('phone_numbers', sa.Column('provider_phone_id', sa.String(length=100), nullable=True))
    
    # Update existing phone numbers to have 'twilio' as provider and copy twilio_sid to provider_phone_id
    op.execute("UPDATE phone_numbers SET provider = 'twilio' WHERE provider IS NULL")
    op.execute("UPDATE phone_numbers SET provider_phone_id = twilio_sid WHERE twilio_sid IS NOT NULL")
    
    # Now make provider column non-nullable
    op.alter_column('phone_numbers', 'provider', nullable=False)
    
    # Drop the old twilio_sid column
    op.drop_column('phone_numbers', 'twilio_sid')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('phone_numbers', sa.Column('twilio_sid', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('phone_numbers', 'provider_phone_id')
    op.drop_column('phone_numbers', 'provider')
    op.drop_column('organizations', 'telnyx_connection_id')
    op.drop_column('organizations', 'telnyx_api_key')
    op.add_column('assistants', sa.Column('phone_number', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.create_unique_constraint('assistants_phone_number_key', 'assistants', ['phone_number'])
    # ### end Alembic commands ###
