"""add phone numbers table and organization twilio credentials

Revision ID: 6f096f9c7da1
Revises: 801c41697c3b
Create Date: 2025-06-24 12:00:18.716675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f096f9c7da1'
down_revision: Union[str, None] = '801c41697c3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('phone_numbers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('friendly_name', sa.String(length=100), nullable=True),
    sa.Column('twilio_sid', sa.String(length=100), nullable=True),
    sa.Column('assistant_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('capabilities', sa.JSON(), nullable=True),
    sa.Column('phone_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assistant_id'], ['assistants.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_phone_numbers_assistant_id'), 'phone_numbers', ['assistant_id'], unique=False)
    op.create_index(op.f('ix_phone_numbers_organization_id'), 'phone_numbers', ['organization_id'], unique=False)
    op.create_index(op.f('ix_phone_numbers_phone_number'), 'phone_numbers', ['phone_number'], unique=True)
    op.add_column('calls', sa.Column('phone_number_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_calls_phone_number_id'), 'calls', ['phone_number_id'], unique=False)
    op.create_foreign_key(None, 'calls', 'phone_numbers', ['phone_number_id'], ['id'])
    op.add_column('organizations', sa.Column('twilio_account_sid', sa.String(length=255), nullable=True))
    op.add_column('organizations', sa.Column('twilio_auth_token', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'twilio_auth_token')
    op.drop_column('organizations', 'twilio_account_sid')
    op.drop_constraint(None, 'calls', type_='foreignkey')
    op.drop_index(op.f('ix_calls_phone_number_id'), table_name='calls')
    op.drop_column('calls', 'phone_number_id')
    op.drop_index(op.f('ix_phone_numbers_phone_number'), table_name='phone_numbers')
    op.drop_index(op.f('ix_phone_numbers_organization_id'), table_name='phone_numbers')
    op.drop_index(op.f('ix_phone_numbers_assistant_id'), table_name='phone_numbers')
    op.drop_table('phone_numbers')
    # ### end Alembic commands ###
