"""update_recording_model_for_twilio

Revision ID: b01a56100ecc
Revises: ca1b038b23cd
Create Date: 2025-05-22 18:43:50.343562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b01a56100ecc'
down_revision: Union[str, None] = 'ca1b038b23cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recordings', sa.Column('recording_sid', sa.String(length=100), nullable=True))
    op.add_column('recordings', sa.Column('recording_url', sa.String(length=500), nullable=True))
    op.add_column('recordings', sa.Column('recording_source', sa.String(length=20), nullable=True))
    op.add_column('recordings', sa.Column('status', sa.String(length=20), nullable=True))
    op.alter_column('recordings', 'file_path',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('recordings', 'file_path',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('recordings', 'status')
    op.drop_column('recordings', 'recording_source')
    op.drop_column('recordings', 'recording_url')
    op.drop_column('recordings', 'recording_sid')
    # ### end Alembic commands ###
