"""rename_recording_metadata_column

Revision ID: bdd2d899e59d
Revises: e646d8e44836
Create Date: 2025-05-25 12:55:34.405755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bdd2d899e59d'
down_revision: Union[str, None] = 'e646d8e44836'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Add new columns first
    op.add_column('recordings', sa.Column('s3_key', sa.String(length=500), nullable=True))
    op.add_column('recordings', sa.Column('s3_url', sa.String(length=1000), nullable=True))
    op.add_column('recordings', sa.Column('s3_bucket', sa.String(length=100), nullable=True))
    op.add_column('recordings', sa.Column('file_size', sa.Integer(), nullable=True))
    op.add_column('recordings', sa.Column('sample_rate', sa.Integer(), nullable=True))
    op.add_column('recordings', sa.Column('channels', sa.Integer(), nullable=True))
    op.add_column('recordings', sa.Column('uploaded_at', sa.DateTime(), nullable=True))
    op.add_column('recordings', sa.Column('recording_metadata', sa.JSON(), nullable=True))
    
    # Update existing records with NULL values to have defaults
    op.execute("UPDATE recordings SET recording_source = 'twilio' WHERE recording_source IS NULL OR recording_source = ''")
    op.execute("UPDATE recordings SET recording_type = 'full' WHERE recording_type IS NULL OR recording_type = ''")
    op.execute("UPDATE recordings SET status = 'completed' WHERE status IS NULL OR status = ''")
    op.execute("UPDATE recordings SET format = 'mp3' WHERE format IS NULL OR format = ''")
    op.execute("UPDATE recordings SET created_at = NOW() WHERE created_at IS NULL")
    
    # Now make columns NOT NULL
    op.alter_column('recordings', 'format',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('recordings', 'recording_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('recordings', 'recording_source',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('recordings', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('recordings', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    
    # Drop old columns
    op.drop_column('recordings', 'file_path')
    op.drop_column('recordings', 'recording_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recordings', sa.Column('recording_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('recordings', sa.Column('file_path', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.alter_column('recordings', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('recordings', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('recordings', 'recording_source',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('recordings', 'recording_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('recordings', 'format',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.drop_column('recordings', 'recording_metadata')
    op.drop_column('recordings', 'uploaded_at')
    op.drop_column('recordings', 'channels')
    op.drop_column('recordings', 'sample_rate')
    op.drop_column('recordings', 'file_size')
    op.drop_column('recordings', 's3_bucket')
    op.drop_column('recordings', 's3_url')
    op.drop_column('recordings', 's3_key')
    # ### end Alembic commands ###
