"""add_tools_settings_to_assistants

Revision ID: c636c2bbb77d
Revises: bdd2d899e59d
Create Date: 2025-05-30 00:45:34.134700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c636c2bbb77d'
down_revision: Union[str, None] = 'bdd2d899e59d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assistants', sa.Column('tools_settings', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assistants', 'tools_settings')
    # ### end Alembic commands ###
