"""assistants model refactored

Revision ID: ca1b038b23cd
Revises: 9ced152e5d7f
Create Date: 2025-05-19 15:42:07.597035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca1b038b23cd'
down_revision: Union[str, None] = '9ced152e5d7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assistants', sa.Column('llm_settings', sa.JSON(), nullable=True))
    op.add_column('assistants', sa.Column('interruption_settings', sa.JSON(), nullable=True))
    op.add_column('assistants', sa.Column('tts_settings', sa.JSON(), nullable=True))
    op.add_column('assistants', sa.Column('stt_settings', sa.JSON(), nullable=True))
    op.drop_column('assistants', 'silence_min_duration_ms')
    op.drop_column('assistants', 'voice_seconds_threshold')
    op.drop_column('assistants', 'elevenlabs_voice_id')
    op.drop_column('assistants', 'system_prompt')
    op.drop_column('assistants', 'openai_temperature')
    op.drop_column('assistants', 'no_punctuation_wait_ms')
    op.drop_column('assistants', 'openai_model')
    op.drop_column('assistants', 'openai_max_tokens')
    op.drop_column('assistants', 'word_count_threshold')
    op.drop_column('assistants', 'wait_after_speech_ms')
    op.drop_column('assistants', 'energy_threshold')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assistants', sa.Column('energy_threshold', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('assistants', sa.Column('wait_after_speech_ms', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('assistants', sa.Column('word_count_threshold', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('assistants', sa.Column('openai_max_tokens', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('assistants', sa.Column('openai_model', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('assistants', sa.Column('no_punctuation_wait_ms', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('assistants', sa.Column('openai_temperature', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('assistants', sa.Column('system_prompt', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('assistants', sa.Column('elevenlabs_voice_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('assistants', sa.Column('voice_seconds_threshold', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('assistants', sa.Column('silence_min_duration_ms', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('assistants', 'stt_settings')
    op.drop_column('assistants', 'tts_settings')
    op.drop_column('assistants', 'interruption_settings')
    op.drop_column('assistants', 'llm_settings')
    # ### end Alembic commands ###
