"""Add background sound settings to assistants

Revision ID: d51bf65b46cb
Revises: 6f9452c61314
Create Date: 2025-05-24 23:32:51.014203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd51bf65b46cb'
down_revision: Union[str, None] = '6f9452c61314'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assistants', sa.Column('background_sound_settings', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_column('assistants', 'background_sound_settings')
    # ### end Alembic commands ###
