"""Add recording settings to assistants

Revision ID: e646d8e44836
Revises: d51bf65b46cb
Create Date: 2025-05-25 10:56:49.295783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e646d8e44836'
down_revision: Union[str, None] = 'd51bf65b46cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assistants', sa.Column('recording_settings', sa.JSON(), nullable=True))
    op.drop_column('assistants', 'background_sound_settings')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assistants', sa.Column('background_sound_settings', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('assistants', 'recording_settings')
    # ### end Alembic commands ###
