"""removed billing models

Revision ID: e8640877db1f
Revises: 6f096f9c7da1
Create Date: 2025-06-25 10:14:57.052520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e8640877db1f'
down_revision: Union[str, None] = '6f096f9c7da1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_usage_records_billing_account_id', table_name='usage_records')
    op.drop_index('ix_usage_records_call_id', table_name='usage_records')
    op.drop_table('usage_records')
    op.drop_index('ix_billing_transactions_billing_account_id', table_name='billing_transactions')
    op.drop_index('ix_billing_transactions_stripe_charge_id', table_name='billing_transactions')
    op.drop_index('ix_billing_transactions_stripe_invoice_id', table_name='billing_transactions')
    op.drop_index('ix_billing_transactions_stripe_payment_intent_id', table_name='billing_transactions')
    op.drop_index('ix_billing_transactions_transaction_type', table_name='billing_transactions')
    op.drop_table('billing_transactions')
    op.drop_index('ix_billing_accounts_organization_id', table_name='billing_accounts')
    op.drop_index('ix_billing_accounts_plan_id', table_name='billing_accounts')
    op.drop_index('ix_billing_accounts_stripe_customer_id', table_name='billing_accounts')
    op.drop_index('ix_billing_accounts_stripe_subscription_id', table_name='billing_accounts')
    op.drop_table('billing_accounts')
    op.drop_table('billing_plans')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('billing_plans',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('billing_plans_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('stripe_price_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('monthly_minutes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('price_cents', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('features', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('sort_order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='billing_plans_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('billing_accounts',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('billing_accounts_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('plan_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('stripe_customer_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('stripe_subscription_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('current_period_minutes_used', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('current_period_start', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('current_period_end', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('auto_topup_enabled', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('topup_threshold_minutes', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('topup_amount_minutes', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('topup_price_cents', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('is_payment_method_attached', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('billing_settings', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name='billing_accounts_organization_id_fkey'),
    sa.ForeignKeyConstraint(['plan_id'], ['billing_plans.id'], name='billing_accounts_plan_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='billing_accounts_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_billing_accounts_stripe_subscription_id', 'billing_accounts', ['stripe_subscription_id'], unique=False)
    op.create_index('ix_billing_accounts_stripe_customer_id', 'billing_accounts', ['stripe_customer_id'], unique=False)
    op.create_index('ix_billing_accounts_plan_id', 'billing_accounts', ['plan_id'], unique=False)
    op.create_index('ix_billing_accounts_organization_id', 'billing_accounts', ['organization_id'], unique=True)
    op.create_table('billing_transactions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('billing_account_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('transaction_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('amount_cents', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('currency', sa.VARCHAR(length=3), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('stripe_payment_intent_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('stripe_invoice_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('stripe_charge_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('minutes_credited', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('billing_period_start', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('billing_period_end', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('transaction_metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['billing_account_id'], ['billing_accounts.id'], name='billing_transactions_billing_account_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='billing_transactions_pkey')
    )
    op.create_index('ix_billing_transactions_transaction_type', 'billing_transactions', ['transaction_type'], unique=False)
    op.create_index('ix_billing_transactions_stripe_payment_intent_id', 'billing_transactions', ['stripe_payment_intent_id'], unique=False)
    op.create_index('ix_billing_transactions_stripe_invoice_id', 'billing_transactions', ['stripe_invoice_id'], unique=False)
    op.create_index('ix_billing_transactions_stripe_charge_id', 'billing_transactions', ['stripe_charge_id'], unique=False)
    op.create_index('ix_billing_transactions_billing_account_id', 'billing_transactions', ['billing_account_id'], unique=False)
    op.create_table('usage_records',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('billing_account_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('call_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('minutes_used', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('usage_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('billing_period_start', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('billing_period_end', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('record_metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['billing_account_id'], ['billing_accounts.id'], name='usage_records_billing_account_id_fkey'),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], name='usage_records_call_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='usage_records_pkey')
    )
    op.create_index('ix_usage_records_call_id', 'usage_records', ['call_id'], unique=False)
    op.create_index('ix_usage_records_billing_account_id', 'usage_records', ['billing_account_id'], unique=False)
    # ### end Alembic commands ###
