"""Add sms_webhook_url to Assistant model

Revision ID: f7c7060547e6
Revises: c66a0d44f5d3
Create Date: 2025-08-20 03:20:21.823703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7c7060547e6'
down_revision: Union[str, None] = 'c66a0d44f5d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assistants', sa.Column('sms_webhook_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assistants', 'sms_webhook_url')
    # ### end Alembic commands ###
